import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SparklesCore } from '@/app/_components/ui/sparkles'
import { Sidebar, SidebarBody } from '@/app/_components/ui/sidebar'
import SidebarComponent from './_components/SidebarComponent'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <div className='absolute inset-0 -z-10'>
          <SparklesCore background='black' speed={2} />
        </div>
        <SidebarComponent />
        {children}
      </body>
    </html>
  )
}
